'use strict';


module.exports = [

	// Equity =================================================================

	{
		name : 'Equity',
		description : '',
		code : '1',
		type : 'equity',
		commodity : 'EUR',
		balance : 0,
		childBalance : 2000,
		aggregatedBalance : 2000,
		placeholder : true,
		closed : false,
		parent : null,
		level : 0
	},

	{
		name : 'Initial state',
		description : '',
		code : '12',
		type : 'equity',
		commodity : 'EUR',
		balance : 2000,
		childBalance : 0,
		aggregatedBalance : 2000,
		placeholder : false,
		closed : false,
		parent : null,
		level : 1
	},

	// Assets =================================================================

	{
		name : 'Assets',
		description : '',
		code : '2',
		type : 'asset',
		commodity : 'EUR',
		balance : 0,
		childBalance : 14300,
		aggregatedBalance : 14300,
		placeholder : true,
		closed : false,
		parent : null,
		level : 0
	},
	{
		name : 'Currents',
		description : '',
		code : '21',
		type : 'asset',
		commodity : 'EUR',
		balance : 0,
		childBalance : 5300,
		aggregatedBalance : 5300,
		placeholder : true,
		closed : false,
		parent : null,
		level : 1
	},
	{
		name : 'Cash',
		description : '',
		code : '211',
		type : 'asset',
		commodity : 'EUR',
		balance : 3300,
		childBalance : 0,
		aggregatedBalance : 3300,
		placeholder : false,
		closed : false,
		parent : null,
		level : 2
	},
	{
		name : 'Savings',
		description : '',
		code : '212',
		type : 'asset',
		commodity : 'EUR',
		balance : 2000,
		childBalance : 0,
		aggregatedBalance : 2000,
		placeholder : false,
		closed : false,
		parent : null,
		level : 2
	},
	{
		name : 'Long-terms',
		description : '',
		code : '22',
		type : 'asset',
		commodity : 'EUR',
		balance : 0,
		childBalance : 9000,
		aggregatedBalance : 9000,
		placeholder : true,
		closed : false,
		parent : null,
		level : 1
	},
	{
		name : 'Real estate',
		description : '',
		code : '221',
		type : 'asset',
		commodity : 'EUR',
		balance : 9000,
		childBalance : 0,
		aggregatedBalance : 9000,
		placeholder : false,
		closed : false,
		parent : null,
		level : 2
	},
	{
		name : 'Companies',
		description : '',
		code : '222',
		type : 'asset',
		commodity : 'EUR',
		balance : 0,
		childBalance : 0,
		aggregatedBalance : 0,
		placeholder : false,
		closed : false,
		parent : null,
		level : 2
	},

	// Liabilities ============================================================

	{
		name : 'Liabilities',
		description : '',
		code : '4',
		type : 'liability',
		commodity : 'EUR',
		balance : 0,
		childBalance : 9300,
		aggregatedBalance : 9300,
		placeholder : true,
		closed : false,
		parent : null,
		level : 0
	},
	{
		name : 'Currents',
		description : '',
		code : '41',
		type : 'liability',
		commodity : 'EUR',
		balance : 0,
		childBalance : 450,
		aggregatedBalance : 450,
		placeholder : true,
		closed : false,
		parent : null,
		level : 1
	},
	{
		name : 'Credit cards',
		description : '',
		code : '411',
		type : 'liability',
		commodity : 'EUR',
		balance : 400,
		childBalance : 0,
		aggregatedBalance : 400,
		placeholder : false,
		closed : false,
		parent : null,
		level : 2
	},
	{
		name : 'Invoices',
		description : '',
		code : '412',
		type : 'liability',
		commodity : 'EUR',
		balance : 50,
		childBalance : 0,
		aggregatedBalance : 50,
		placeholder : false,
		closed : false,
		parent : null,
		level : 2
	},
	{
		name : 'Long-terms',
		description : '',
		code : '42',
		type : 'liability',
		commodity : 'EUR',
		balance : 0,
		childBalance : 8850,
		aggregatedBalance : 8850,
		placeholder : true,
		closed : false,
		parent : null,
		level : 1
	},
	{
		name : 'Loans',
		description : '',
		code : '421',
		type : 'liability',
		commodity : 'EUR',
		balance : 8850,
		childBalance : 0,
		aggregatedBalance : 8850,
		placeholder : false,
		closed : false,
		parent : null,
		level : 2
	},

	// Incomes ================================================================

	{
		name : 'Incomes',
		description : '',
		code : '7',
		type : 'income',
		commodity : 'EUR',
		balance : 0,
		childBalance : 4650,
		aggregatedBalance : 4650,
		placeholder : true,
		closed : false,
		parent : null,
		level : 0
	},
	{
		name : 'Recurring',
		description : '',
		code : '71',
		type : 'income',
		commodity : 'EUR',
		balance : 0,
		childBalance : 3650,
		aggregatedBalance : 3650,
		placeholder : true,
		closed : false,
		parent : null,
		level : 1
	},
	{
		name : 'Salaries',
		description : '',
		code : '711',
		type : 'income',
		commodity : 'EUR',
		balance : 3000,
		childBalance : 0,
		aggregatedBalance : 3000,
		placeholder : false,
		closed : false,
		parent : null,
		level : 2
	},
	{
		name : 'Rents',
		description : '',
		code : '712',
		type : 'income',
		commodity : 'EUR',
		balance : 650,
		childBalance : 0,
		aggregatedBalance : 650,
		placeholder : false,
		closed : false,
		parent : null,
		level : 2
	},
	{
		name : 'Exceptional',
		description : '',
		code : '72',
		type : 'income',
		commodity : 'EUR',
		balance : 0,
		childBalance : 1000,
		aggregatedBalance : 1000,
		placeholder : true,
		closed : false,
		parent : null,
		level : 1
	},
	{
		name : 'Salaries',
		description : '',
		code : '721',
		type : 'income',
		commodity : 'EUR',
		balance : 1000,
		childBalance : 0,
		aggregatedBalance : 1000,
		placeholder : false,
		closed : false,
		parent : null,
		level : 2
	},

	// Expenses ===============================================================

	{
		name : 'Expenses',
		description : '',
		code : '6',
		type : 'expense',
		commodity : 'EUR',
		balance : 0,
		childBalance : 1650,
		aggregatedBalance : 1650,
		placeholder : true,
		closed : false,
		parent : null,
		level : 0
	},
	{
		name : 'Recurring',
		description : '',
		code : '61',
		type : 'expense',
		commodity : 'EUR',
		balance : 0,
		childBalance : 1150,
		aggregatedBalance : 1150,
		placeholder : true,
		closed : false,
		parent : null,
		level : 1
	},
	{
		name : 'House',
		description : '',
		code : '611',
		type : 'expense',
		commodity : 'EUR',
		balance : 800,
		childBalance : 0,
		aggregatedBalance : 800,
		placeholder : false,
		closed : false,
		parent : null,
		level : 2
	},
	{
		name : 'Financial fees',
		description : '',
		code : '612',
		type : 'expense',
		commodity : 'EUR',
		balance : 50,
		childBalance : 0,
		aggregatedBalance : 50,
		placeholder : false,
		closed : false,
		parent : null,
		level : 2
	},
	{
		name : 'Real estate',
		description : '',
		code : '613',
		type : 'expense',
		commodity : 'EUR',
		balance : 300,
		childBalance : 0,
		aggregatedBalance : 300,
		placeholder : false,
		closed : false,
		parent : null,
		level : 2
	},
	{
		name : 'Exceptional',
		description : '',
		code : '62',
		type : 'expense',
		commodity : 'EUR',
		balance : 0,
		childBalance : 500,
		aggregatedBalance : 500,
		placeholder : true,
		closed : false,
		parent : null,
		level : 1
	},
	{
		name : 'Misc',
		description : '',
		code : '621',
		type : 'expense',
		commodity : 'EUR',
		balance : 500,
		childBalance : 0,
		aggregatedBalance : 500,
		placeholder : false,
		closed : false,
		parent : null,
		level : 2
	}

];